# Generated by Django 2.2.3 on 2019-10-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('caption', models.CharField(max_length=500)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
