# Generated by Django 2.2.4 on 2019-12-14 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20191029_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('src', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoId', models.CharField(max_length=100)),
                ('caption', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Media',
        ),
    ]
