# Generated by Django 2.2.3 on 2019-07-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading2', models.CharField(max_length=200)),
                ('body2', models.CharField(max_length=5000)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='heading',
            new_name='heading1',
        ),
        migrations.AddField(
            model_name='event',
            name='body1',
            field=models.CharField(default=11, max_length=5000),
            preserve_default=False,
        ),
    ]
