# Generated by Django 2.2.3 on 2019-07-24 19:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190723_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date2',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='date1',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='body1',
            field=models.TextField(),
        ),
    ]
