# Generated by Django 2.2.4 on 2019-12-14 21:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191030_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField(default=datetime.date.today)),
                ('body', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
