# Generated by Django 2.2.4 on 2019-12-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('info', models.CharField(max_length=5000)),
                ('year', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(default='')),
                ('exec_position', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('part', models.CharField(max_length=200)),
                ('src', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('years', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
