# Generated by Django 2.2.3 on 2019-07-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='year',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='current',
            name='exec',
            field=models.CharField(default='', max_length=200),
        ),
    ]
