# Generated by Django 2.2.3 on 2019-10-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20191029_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='current',
            old_name='exec',
            new_name='execPosition',
        ),
        migrations.RenameField(
            model_name='current',
            old_name='image',
            new_name='src',
        ),
        migrations.AddField(
            model_name='current',
            name='years',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='current',
            name='bio',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
