# Generated by Django 2.2.3 on 2019-10-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20191029_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='is_exec',
            field=models.BooleanField(default=False),
        ),
    ]
