# Generated by Django 2.2.3 on 2019-10-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_current_is_exec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='execPosition',
            field=models.CharField(default='n\x07', max_length=200),
        ),
    ]
