# Generated by Django 2.2.3 on 2019-10-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20191029_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='execPosition',
            field=models.CharField(default='', max_length=200),
        ),
    ]
