# Generated by Django 2.2.4 on 2019-11-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20191029_0238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='is_exec',
        ),
        migrations.AddField(
            model_name='current',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='current',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
