# Generated by Django 2.2.4 on 2019-11-07 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20191106_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
