# Generated by Django 2.2.4 on 2019-12-14 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_auto_20191107_0630'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Current',
            new_name='Member',
        ),
    ]
